# Generated by Django 4.0.6 on 2022-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('Job_locations', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
